### ISSUE TITLE
Admin Frontend

### ISSUE THREAD

**Issue by nicolas-semaphor** [semaphor-dk/voxpop#17]
We need a "watered down" version of the Django interface that allows authenticated users to view Voxpops relevant to their organisation as well as moderate the chats of the Voxpops.

I think the site will be accesible like this:
voxpop.semaphor.dk/admin <- General overview
voxpop.semaphor.dk/admin/<voxpop.uuid> <- Specific voxpop overview.

And potentially we can use the @login_required decorater around the specific views to ensure only authorized personall can access the site.

**Comment by bofrede** [comment]
Done.
