### ISSUE TITLE
Database connection leak on SSE requests

### ISSUE THREAD

**Issue by bofrede** [semaphor-dk/voxpop#27]
The database connections used for SSE are not closed, witch leads to not available database connections, as they are all used.

The `EventSource` at `/voxpops/<voxpopid>/questions/stream` calls `questions_stream_view` witch returns a `StreamingHttpResponse` in 

https://github.com/semaphor-dk/voxpop/blob/f26ca8b7cbb96bc3805aa07bb589971f19e5eafe/voxpop/views.py#L237-L245

Inside `__stream_questions` some async code yields the events:

https://github.com/semaphor-dk/voxpop/blob/f26ca8b7cbb96bc3805aa07bb589971f19e5eafe/voxpop/views.py#L220-L224

This async block needs to be stopped and the database connection closed, when the HTTP connection is dropped.

**Comment by bofrede** [comment]
There is a branch with some print statements: https://github.com/semaphor-dk/voxpop/blob/debug_sse/voxpop/views.py

**Comment by valberg** [comment]
Yeah - so this is a big drawback of the solution using LISTEN/NOTIFY (see for instance the lobste.rs comments to my blogpost: https://lobste.rs/s/qyler8/writing_chat_application_django_4_2_using)

I guess the only real solution is to stop using LISTEN/NOTIFY and instead use redis (or similiar) to be the queue.

**Comment by valberg** [comment]
I can try to come up with a solution soonish

**Comment by nicolas-semaphor** [comment]
This issue appears to be resolved after replacing LISTEN/NOTIFY with Redis, thus I'm closing this issue :-)
